on: [push]
jobs:
  setup:
    runs-on: windows-latest
    steps:
      - run: node --version
  build:
    needs: setup
    runs-on: windows-latest
    steps:
      - run: node --version
  test:
    needs: build
    runs-on: windows-latest
    steps:
      - run: node --version
