on: [push]
jobs:
  job-1:
    runs-on: windows-latest
    steps:
      - run: node --version
  job-2:
    needs: job-1
    runs-on: windows-latest
    steps:
      - run: npm --version
  job-3:
    needs: job-2
    runs-on: windows-latest
    steps:
      - run: echo "Hello, World!"
